services:
  - type: web
    name: knowbie-client
    env: static
    buildCommand: cd Client && npm install && npm run build
    staticPublishPath: Client/dist
    envVars:
      - key: VITE_API_URL
        value: "https://knowbie-server.onrender.com"