- type: web
  name: knowbie-client
  env: static
  buildCommand: cd Client && npm install && npm run build
  staticPublishPath: Client/dist
  headers:
    - source: "**"
      headers:
        - key: "Access-Control-Allow-Origin"
          value: "*"
  routes:
    - type: rewrite
      source: /*
      destination: /index.html